Create index.html
MarieMatsumoto/html-css-nri pull request #1
Opened 2020-09-17 14:06 UTC by MarieMatsumoto

課題提出用

2020-09-20 04:26 UTC, ykyk1218 requested changes

2020-09-20 04:26 UTC, ykyk1218 commented on index.html
> +    <link rel="stylesheet" href="/Users/marie/Desktop/3rd-week/nri-html/style.css">
今回はcssは特に見ないので良いですが、このパスだと他の人のpcで見たときにcssが見れないですね😵

2020-09-20 04:26 UTC, ykyk1218 commented on index.html
> +            <div class="flexbox-1">
class名はもう少し意味のある名前をつけてあげた方が良いですね😌

2020-09-20 04:26 UTC, ykyk1218 commented on index.html
> +                <h2>NRIのデジタルビジネス戦略</h2>
h1タグが見当たらなかったです。(あったらごめんなさい)
h1がなくてh2があるのは構成的におかしいので、確認をお願いします！

2020-09-20 08:16 UTC, MarieMatsumoto commented on index.html
> +    <link rel="stylesheet" href="/Users/marie/Desktop/3rd-week/nri-html/style.css">
ローカル環境のまま上げていました。CSS課題のほうで反映させるようにいたします。

2020-09-20 08:17 UTC, MarieMatsumoto commented on index.html
> +                <h2>NRIのデジタルビジネス戦略</h2>
すみません、H1が抜けていました。ここをH2からH1に変更します。

2020-09-20 08:21 UTC, MarieMatsumoto commented on index.html
> +            <div class="flexbox-1">
すみません、適当すぎました…。変更します。

2020-09-20 08:26 UTC, MarieMatsumoto reviewed
スタイルシートの参照元URLを一旦空欄に、クラス名を変更、見出しの番号変更

2020-09-20 13:17 UTC, ykyk1218 commented on index.html
> +                <div class="global-navi">
ナビゲーションはナビゲーション用のタグがあるのでそっちを使ってあげたほうが良いですね

2020-09-20 13:17 UTC, ykyk1218 commented on index.html
> +                    <h4>NRIの強み</h4>
ここが h4 の場合はこれの前に h3 がある必要があります。

2020-09-20 13:17 UTC, ykyk1218 commented on index.html
> +                <h3>企業情報</h3>
階層構造的にここが h3 の場合は ` <h2 class="main-h2">NRIのデジタルビジネス戦略</h2>` の下にコンテンツが存在しているイメージになるのですが、そんなことはないと思うので、h3 ではない方が良さそうです。

この辺はメインのコンテンツから外れていることもあるので、見出しタグは使わなくても良さそうですね 😄

2020-09-20 13:17 UTC, ykyk1218 commented on index.html
> +            <h4><a href="#">ナレッジ・インサイト</a></h4>
この辺も見出しタグは使わなくても良いかと思います！

2020-09-20 13:43 UTC, ykyk1218 commented
追加で！
head タグ内に discriptionやkeywords、OGPのmetaタグの追加をお願いします！

2020-09-20 14:26 UTC, MarieMatsumoto commented on index.html
> +                    <h4>NRIの強み</h4>
ここをH3に修正します。

2020-09-20 14:45 UTC, MarieMatsumoto commented on index.html
> +                <h3>企業情報</h3>
すべてpタグに変更します。

2020-09-20 15:11 UTC, MarieMatsumoto commented on index.html
> +                <div class="global-navi">
修正しました。

2020-09-22 01:57 UTC, ykyk1218 commented
良さそうです！！
LGTM 👍

2020-09-22 02:37 UTC, merged